services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=172.31.2.16
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=produtos_db
      - DB_PORT=3306
    volumes:
      - /mnt/efs:/app/public/uploads
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
